### ISSUE TITLE
api_client.py: __deserialize_file fails on utf-8 content 

### ISSUE THREAD

**Issue by yacobi** [phrase/phrase-python#5]
Download locale and saving to a file fails when the response contains utf-8 chars. 

`  File "E:\tools\python\3.6.8\lib\site-packages\phrase_api\api_client.py", line 255, in deserialize
    return self.__deserialize_file(response)
  File "E:\tools\python\3.6.8\lib\site-packages\phrase_api\api_client.py", line 558, in __deserialize_file
    f.write(response.data)
  File "E:\tools\python\3.6.8\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 43-48: character maps to <undefined>`

This can be solved changing api_client.py line 557/560 to: 

```
            with open(path, "w", encoding="utf-8") as f:
                f.write(response.data)
```

**Comment by jablan** [comment]
@yacobi, thanks for reporting this and suggesting a solution! would this break functionality for people actually wanting to use non-utf encodings? have you perhaps tried changing the global default on your system (https://stackoverflow.com/questions/31469707/changing-the-locale-preferred-encoding-in-python-3-in-windows)?

**Comment by yacobi** [comment]
HI @jablan, Thanks for your quick response. Let me check it and I will get back to you.

**Comment by jablan** [comment]
Should be solved by the linked PR. @yacobi please check it out, if it solves your problem.
