### ISSUE TITLE
phrase doesn't escape meta_char when downloading local

### ISSUE THREAD

**Issue by yacobi** [phrase/phrase-python#6]
Hi All, 

Regarding locale_api.locale_download(...)

Although per default escape_meta_chars should be true for Java properties format(https://support.phrase.com/hc/en-us/articles/5784070560412),  The meta chars in the downloaded .properties files are not escaped. 

See example attached. (changed extension because .properties not supported here)
[MessagesBundle_RS-rs.txt](https://github.com/phrase/phrase-python/files/9947319/MessagesBundle_RS-rs.txt)

**Comment by jablan** [comment]
hi @yacobi. Which line in the attached file are you referring to? `escape_meta_characters`, according to the documentation you linked, refers to characters `!`, `:` and `=`.

**Comment by jablan** [comment]
The escaping only applies to the content itself, i.e. everything _after_ the first equals character. An example of escaped `=` characters can be seen at line 8799 for example:

    TI_CentralHeatingPumpPerformance_Desc = Einstellungen für die Restförderhöhe der Primärkreispumpe\nDruckverlust\:\nNicht einstellen.\nGrenzwert\: \n0 \= Primärkreispumpe wird außentemperaturabhängig gesteuert.\n>0 \= Primärkreispumpe wird mit konstanter Restförderhöhe betrieben.\nSteigung\:\n0 \= Primärkreispumpe wird mit konstantem Differenzdruck betrieben.\n>0 \= Primärkreispumpe wird mit ansteigendem Differenzdruck betrieben.\n

**Comment by yacobi** [comment]
I see. Meaning caller has to take care of every metachar before. Thanks for clarifying that
