### ISSUE TITLE
How to upload a source for a job

### ISSUE THREAD

**Issue by ekohl** [phrase/phrase-python#7]
When I look in the API docs I see https://cloud.memsource.com/web/docs/api#operation/createJob which can upload files, but the Python API doesn't appear to expose this part in `create_job`.

Then I also see https://cloud.memsource.com/web/docs/api#operation/updateSource but this whole endpoint doesn't appear to exist within the API.

**Comment by jablan** [comment]
hey @ekohl, there are two Phrase products. This library is the client for Phrase Strings, whose API is documented here: https://developers.phrase.com/api/#overview
